// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i10;
import 'dart:convert' as _i29;
import 'dart:typed_data' as _i30;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i15;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i2;
import 'package:ditonton/data/models/movie_model.dart' as _i14;
import 'package:ditonton/data/models/tv_detail_model.dart' as _i5;
import 'package:ditonton/data/models/tv_model.dart' as _i20;
import 'package:ditonton/data/models/watchlist_model.dart' as _i12;
import 'package:ditonton/data/services/database_service.dart' as _i9;
import 'package:ditonton/data/sources/movie_remote_data_source.dart' as _i13;
import 'package:ditonton/data/sources/tv_remote_data_source.dart' as _i19;
import 'package:ditonton/data/sources/watchlist_local_data_source.dart' as _i27;
import 'package:ditonton/domain/entities/movie.dart' as _i16;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i17;
import 'package:ditonton/domain/entities/tv.dart' as _i21;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i22;
import 'package:ditonton/domain/entities/watchlist.dart' as _i25;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i4;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i6;
import 'package:ditonton/domain/repositories/watchlist_repository.dart' as _i7;
import 'package:ditonton/domain/usecases/detail.dart' as _i24;
import 'package:ditonton/domain/usecases/movie.dart' as _i18;
import 'package:ditonton/domain/usecases/search.dart' as _i26;
import 'package:ditonton/domain/usecases/tv.dart' as _i23;
import 'package:ditonton/domain/usecases/watchlist.dart' as _i28;
import 'package:http/http.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieDetailModel_0 extends _i1.Fake implements _i2.MovieDetailModel {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeMovieRepository_2 extends _i1.Fake implements _i4.MovieRepository {}

class _FakeTvDetailModel_3 extends _i1.Fake implements _i5.TvDetailModel {}

class _FakeTvRepository_4 extends _i1.Fake implements _i6.TvRepository {}

class _FakeWatchlistRepository_5 extends _i1.Fake
    implements _i7.WatchlistRepository {}

class _FakeResponse_6 extends _i1.Fake implements _i8.Response {}

class _FakeStreamedResponse_7 extends _i1.Fake implements _i8.StreamedResponse {
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i9.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(Invocation.getter(#tableName), returnValue: '')
          as String);
  @override
  _i10.Future<_i11.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i11.Database?>.value())
          as _i10.Future<_i11.Database?>);
  @override
  _i10.Future<int> insert(_i12.WatchlistModel? watchlistModel) =>
      (super.noSuchMethod(Invocation.method(#insert, [watchlistModel]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<List<_i12.WatchlistModel>> findAll() => (super.noSuchMethod(
          Invocation.method(#findAll, []),
          returnValue:
              Future<List<_i12.WatchlistModel>>.value(<_i12.WatchlistModel>[]))
      as _i10.Future<List<_i12.WatchlistModel>>);
  @override
  _i10.Future<bool> findById(int? id, int? isMovie) =>
      (super.noSuchMethod(Invocation.method(#findById, [id, isMovie]),
          returnValue: Future<bool>.value(false)) as _i10.Future<bool>);
  @override
  _i10.Future<int> remove(_i12.WatchlistModel? watchlistModel) =>
      (super.noSuchMethod(Invocation.method(#remove, [watchlistModel]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i13.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i14.MovieModel>> getNowPlaying() => (super.noSuchMethod(
          Invocation.method(#getNowPlaying, []),
          returnValue: Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]))
      as _i10.Future<List<_i14.MovieModel>>);
  @override
  _i10.Future<_i2.MovieDetailModel> getDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetail, [id]),
              returnValue:
                  Future<_i2.MovieDetailModel>.value(_FakeMovieDetailModel_0()))
          as _i10.Future<_i2.MovieDetailModel>);
  @override
  _i10.Future<List<_i14.MovieModel>> getRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendations, [id]),
              returnValue:
                  Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]))
          as _i10.Future<List<_i14.MovieModel>>);
  @override
  _i10.Future<List<_i14.MovieModel>> getPopular() => (super.noSuchMethod(
          Invocation.method(#getPopular, []),
          returnValue: Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]))
      as _i10.Future<List<_i14.MovieModel>>);
  @override
  _i10.Future<List<_i14.MovieModel>> getTopRated() => (super.noSuchMethod(
          Invocation.method(#getTopRated, []),
          returnValue: Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]))
      as _i10.Future<List<_i14.MovieModel>>);
  @override
  _i10.Future<List<_i14.MovieModel>> search(String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [query]),
              returnValue:
                  Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]))
          as _i10.Future<List<_i14.MovieModel>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i4.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getNowPlaying() =>
      (super.noSuchMethod(Invocation.method(#getNowPlaying, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getPopular() =>
      (super.noSuchMethod(Invocation.method(#getPopular, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, _i17.MovieDetail>> getDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetail, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, _i17.MovieDetail>>.value(
              _FakeEither_1<_i15.Failure, _i17.MovieDetail>())) as _i10
          .Future<_i3.Either<_i15.Failure, _i17.MovieDetail>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendations, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> search(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [query]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
}

/// A class which mocks [MovieUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieUsecase extends _i1.Mock implements _i18.MovieUsecase {
  MockMovieUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get movieRepository =>
      (super.noSuchMethod(Invocation.getter(#movieRepository),
          returnValue: _FakeMovieRepository_2()) as _i4.MovieRepository);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getNowPlaying() =>
      (super.noSuchMethod(Invocation.method(#getNowPlaying, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getPopular() =>
      (super.noSuchMethod(Invocation.method(#getPopular, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i19.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i20.TvModel>> onTheAir() =>
      (super.noSuchMethod(Invocation.method(#onTheAir, []),
              returnValue: Future<List<_i20.TvModel>>.value(<_i20.TvModel>[]))
          as _i10.Future<List<_i20.TvModel>>);
  @override
  _i10.Future<_i5.TvDetailModel> getDetail(int? id) => (super.noSuchMethod(
          Invocation.method(#getDetail, [id]),
          returnValue: Future<_i5.TvDetailModel>.value(_FakeTvDetailModel_3()))
      as _i10.Future<_i5.TvDetailModel>);
  @override
  _i10.Future<List<_i20.TvModel>> getRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendations, [id]),
              returnValue: Future<List<_i20.TvModel>>.value(<_i20.TvModel>[]))
          as _i10.Future<List<_i20.TvModel>>);
  @override
  _i10.Future<List<_i20.TvModel>> getPopular() =>
      (super.noSuchMethod(Invocation.method(#getPopular, []),
              returnValue: Future<List<_i20.TvModel>>.value(<_i20.TvModel>[]))
          as _i10.Future<List<_i20.TvModel>>);
  @override
  _i10.Future<List<_i20.TvModel>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
              returnValue: Future<List<_i20.TvModel>>.value(<_i20.TvModel>[]))
          as _i10.Future<List<_i20.TvModel>>);
  @override
  _i10.Future<List<_i20.TvModel>> search(String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [query]),
              returnValue: Future<List<_i20.TvModel>>.value(<_i20.TvModel>[]))
          as _i10.Future<List<_i20.TvModel>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i6.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> onTheAir() =>
      (super.noSuchMethod(Invocation.method(#onTheAir, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getPopular() =>
      (super.noSuchMethod(Invocation.method(#getPopular, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, _i22.TvDetail>> getDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetail, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, _i22.TvDetail>>.value(
              _FakeEither_1<_i15.Failure, _i22.TvDetail>())) as _i10
          .Future<_i3.Either<_i15.Failure, _i22.TvDetail>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendations, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> search(String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [query]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
}

/// A class which mocks [TvUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvUsecase extends _i1.Mock implements _i23.TvUsecase {
  MockTvUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get tvRepository =>
      (super.noSuchMethod(Invocation.getter(#tvRepository),
          returnValue: _FakeTvRepository_4()) as _i6.TvRepository);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> onTheAir() =>
      (super.noSuchMethod(Invocation.method(#onTheAir, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getPopular() =>
      (super.noSuchMethod(Invocation.method(#getPopular, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
}

/// A class which mocks [DetailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailUsecase extends _i1.Mock implements _i24.DetailUsecase {
  MockDetailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get movieRepository =>
      (super.noSuchMethod(Invocation.getter(#movieRepository),
          returnValue: _FakeMovieRepository_2()) as _i4.MovieRepository);
  @override
  _i6.TvRepository get tvRepository =>
      (super.noSuchMethod(Invocation.getter(#tvRepository),
          returnValue: _FakeTvRepository_4()) as _i6.TvRepository);
  @override
  _i7.WatchlistRepository get watchlistRepository => (super.noSuchMethod(
      Invocation.getter(#watchlistRepository),
      returnValue: _FakeWatchlistRepository_5()) as _i7.WatchlistRepository);
  @override
  _i10.Future<_i3.Either<_i15.Failure, _i17.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, _i17.MovieDetail>>.value(
              _FakeEither_1<_i15.Failure, _i17.MovieDetail>())) as _i10
          .Future<_i3.Either<_i15.Failure, _i17.MovieDetail>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>
      getMovieRecommendations(dynamic id) => (super.noSuchMethod(
          Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, _i22.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, _i22.TvDetail>>.value(
              _FakeEither_1<_i15.Failure, _i22.TvDetail>())) as _i10
          .Future<_i3.Either<_i15.Failure, _i22.TvDetail>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> getTvRecommendations(
          dynamic id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, bool>> isWatchlisted(
          int? id, int? isMovie) =>
      (super.noSuchMethod(Invocation.method(#isWatchlisted, [id, isMovie]),
              returnValue: Future<_i3.Either<_i15.Failure, bool>>.value(
                  _FakeEither_1<_i15.Failure, bool>()))
          as _i10.Future<_i3.Either<_i15.Failure, bool>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, String>> save(
          _i25.Watchlist? watchlist) =>
      (super.noSuchMethod(Invocation.method(#save, [watchlist]),
              returnValue: Future<_i3.Either<_i15.Failure, String>>.value(
                  _FakeEither_1<_i15.Failure, String>()))
          as _i10.Future<_i3.Either<_i15.Failure, String>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, String>> remove(
          _i25.Watchlist? watchlist) =>
      (super.noSuchMethod(Invocation.method(#remove, [watchlist]),
              returnValue: Future<_i3.Either<_i15.Failure, String>>.value(
                  _FakeEither_1<_i15.Failure, String>()))
          as _i10.Future<_i3.Either<_i15.Failure, String>>);
}

/// A class which mocks [SearchUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchUsecase extends _i1.Mock implements _i26.SearchUsecase {
  MockSearchUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get movieRepository =>
      (super.noSuchMethod(Invocation.getter(#movieRepository),
          returnValue: _FakeMovieRepository_2()) as _i4.MovieRepository);
  @override
  _i6.TvRepository get tvRepository =>
      (super.noSuchMethod(Invocation.getter(#tvRepository),
          returnValue: _FakeTvRepository_4()) as _i6.TvRepository);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i16.Movie>>> searchMovie(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovie, [query]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>.value(
              _FakeEither_1<_i15.Failure, List<_i16.Movie>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i16.Movie>>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i21.Tv>>> searchTv(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
          returnValue: Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>.value(
              _FakeEither_1<_i15.Failure, List<_i21.Tv>>())) as _i10
          .Future<_i3.Either<_i15.Failure, List<_i21.Tv>>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i27.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<int> insertWatchlist(_i12.WatchlistModel? watchlistModel) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [watchlistModel]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<int> removeWatchlist(_i12.WatchlistModel? watchlistModel) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [watchlistModel]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<bool> getWatchlistById(int? id, int? isMovie) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistById, [id, isMovie]),
          returnValue: Future<bool>.value(false)) as _i10.Future<bool>);
  @override
  _i10.Future<List<_i12.WatchlistModel>> getAllWatchlist() =>
      (super.noSuchMethod(Invocation.method(#getAllWatchlist, []),
              returnValue: Future<List<_i12.WatchlistModel>>.value(
                  <_i12.WatchlistModel>[]))
          as _i10.Future<List<_i12.WatchlistModel>>);
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i7.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.Either<_i15.Failure, String>> save(
          _i25.Watchlist? watchlist) =>
      (super.noSuchMethod(Invocation.method(#save, [watchlist]),
              returnValue: Future<_i3.Either<_i15.Failure, String>>.value(
                  _FakeEither_1<_i15.Failure, String>()))
          as _i10.Future<_i3.Either<_i15.Failure, String>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, String>> remove(
          _i25.Watchlist? watchlist) =>
      (super.noSuchMethod(Invocation.method(#remove, [watchlist]),
              returnValue: Future<_i3.Either<_i15.Failure, String>>.value(
                  _FakeEither_1<_i15.Failure, String>()))
          as _i10.Future<_i3.Either<_i15.Failure, String>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, bool>> isWatchlisted(
          int? id, int? isMovie) =>
      (super.noSuchMethod(Invocation.method(#isWatchlisted, [id, isMovie]),
              returnValue: Future<_i3.Either<_i15.Failure, bool>>.value(
                  _FakeEither_1<_i15.Failure, bool>()))
          as _i10.Future<_i3.Either<_i15.Failure, bool>>);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>> getWatchlists() =>
      (super.noSuchMethod(Invocation.method(#getWatchlists, []),
              returnValue:
                  Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>>.value(
                      _FakeEither_1<_i15.Failure, List<_i25.Watchlist>>()))
          as _i10.Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>>);
}

/// A class which mocks [WatchlistUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistUsecase extends _i1.Mock implements _i28.WatchlistUsecase {
  MockWatchlistUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.WatchlistRepository get watchlistRepository => (super.noSuchMethod(
      Invocation.getter(#watchlistRepository),
      returnValue: _FakeWatchlistRepository_5()) as _i7.WatchlistRepository);
  @override
  _i10.Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>> getWatchlists() =>
      (super.noSuchMethod(Invocation.method(#getWatchlists, []),
              returnValue:
                  Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>>.value(
                      _FakeEither_1<_i15.Failure, List<_i25.Watchlist>>()))
          as _i10.Future<_i3.Either<_i15.Failure, List<_i25.Watchlist>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i8.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i8.Response>.value(_FakeResponse_6()))
          as _i10.Future<_i8.Response>);
  @override
  _i10.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<_i30.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i30.Uint8List>.value(_i30.Uint8List(0)))
          as _i10.Future<_i30.Uint8List>);
  @override
  _i10.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i8.StreamedResponse>.value(_FakeStreamedResponse_7()))
          as _i10.Future<_i8.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
